baseurl         = "https://reuse.software/"
languageCode    = "en-us"
title           = "REUSE Initiative"
theme           = "github-project-landing-page"

#[permalinks]
#        page = "/:title/"
#        about = "/:filename/"


[params]
    description = "Best practices on adding license information in ways which not only humans can read, but computers as well. Machine readable copyright and license information, simply put!"

    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"
